// <auto-generated />
using System;
using FitnessTracker.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitnessTracker.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FitnessTracker.Api.Models.BodyMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ArmsCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("BodyFatPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("ChestCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal?>("HipsCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("ThighsCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("WaistCm")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("BodyMetrics");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Equipment")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Category = 0,
                            Equipment = "Barbell",
                            Name = "Barbell Bench Press"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Category = 4,
                            Equipment = "Barbell",
                            Name = "Back Squat"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Category = 1,
                            Equipment = "Barbell",
                            Name = "Conventional Deadlift"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            Category = 2,
                            Equipment = "Barbell",
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            Category = 1,
                            Equipment = "Bodyweight",
                            Name = "Pull-Up"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            Category = 1,
                            Equipment = "Barbell",
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            Category = 3,
                            Equipment = "Dumbbell",
                            Name = "Dumbbell Bicep Curl"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111108"),
                            Category = 3,
                            Equipment = "Cable",
                            Name = "Tricep Pushdown"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111109"),
                            Category = 4,
                            Equipment = "Machine",
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111110"),
                            Category = 5,
                            Equipment = "Bodyweight",
                            Name = "Plank"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = 6,
                            Equipment = "Treadmill",
                            Name = "Treadmill Run"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            Category = 4,
                            Equipment = "Dumbbell",
                            Name = "Walking Lunges"
                        });
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.TemplateExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("TargetReps")
                        .HasColumnType("integer");

                    b.Property<int>("TargetSets")
                        .HasColumnType("integer");

                    b.Property<decimal?>("TargetWeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateExercises");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Completed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int?>("Rpe")
                        .HasColumnType("integer");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SetNumber")
                        .HasColumnType("integer");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("SessionId");

                    b.ToTable("WorkoutSets");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutTemplates");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.BodyMetric", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.User", "User")
                        .WithMany("BodyMetrics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Exercise", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.User", "User")
                        .WithMany("Exercises")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.TemplateExercise", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.Exercise", "Exercise")
                        .WithMany("TemplateExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Api.Models.WorkoutTemplate", "Template")
                        .WithMany("Exercises")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutSession", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.WorkoutTemplate", "Template")
                        .WithMany("Sessions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FitnessTracker.Api.Models.User", "User")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutSet", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.Exercise", "Exercise")
                        .WithMany("WorkoutSets")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FitnessTracker.Api.Models.WorkoutSession", "Session")
                        .WithMany("Sets")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutTemplate", b =>
                {
                    b.HasOne("FitnessTracker.Api.Models.User", "User")
                        .WithMany("WorkoutTemplates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.Exercise", b =>
                {
                    b.Navigation("TemplateExercises");

                    b.Navigation("WorkoutSets");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.User", b =>
                {
                    b.Navigation("BodyMetrics");

                    b.Navigation("Exercises");

                    b.Navigation("WorkoutSessions");

                    b.Navigation("WorkoutTemplates");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutSession", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("FitnessTracker.Api.Models.WorkoutTemplate", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
